### ISSUE TITLE
upload .jpg files don't work

### ISSUE THREAD

**Issue by sinelga** [danjac/photoshare#1]
I successfully install yours application but unfortunately can't upload .jpg files but from other side .png and .gif successfully uploaded

  CHECKING image/jpeg
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x58e0e0]

goroutine 49 [running]:
runtime.panic(0xb26a60, 0xfd78d3)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
code.google.com/p/graphics-go/graphics.Thumbnail(0x7fae1580cbf0, 0xc208045280, 0x0, 0x0, 0x0, 0x0)
        /home/juno/workspace/gocode/src/code.google.com/p/graphics-go/graphics/thumbnail.go:15 +0x50
github.com/danjac/photoshare.(*defaultFileStorage).store(0xc2080be0c0, 0x7fae1580c9b8, 0xc208152ea0, 0xc20823c0e0, 0x14, 0xc2081a08c0, 0xa, 0x0, 0x0)
        /home/juno/workspace/gocode/src/github.com/danjac/photoshare/storage.go:128 +0x446
github.com/danjac/photoshare.func·009()
        /home/juno/workspace/gocode/src/github.com/danjac/photoshare/photos.go:147 +0xc0
created by github.com/danjac/photoshare.upload
        /home/juno/workspace/gocode/src/github.com/danjac/photoshare/photos.go:151 +0x5ae

goroutine 16 [IO wait]:
net.runtime_pollWait(0x7fae157fed38, 0x72, 0x0)
        /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(_pollDesc).Wait(0xc2080f34f0, 0x72, 0x0, 0x0)
        /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(_pollDesc).WaitRead(0xc2080f34f0, 0x0, 0x0)
        /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(_netFD).accept(0xc2080f3490, 0xd518e8, 0x0, 0x7fae157fd2b8, 0xb)
        /usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(_TCPListener).AcceptTCP(0xc208034550, 0x463c23, 0x0, 0x0)
        /usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net/http.tcpKeepAliveListener.Accept(0xc208034550, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/pkg/net/http/server.go:1947 +0x4b
net/http.(_Server).Serve(0xc2080fe480, 0x7fae158078c8, 0xc208034550, 0x0, 0x0)
        /usr/local/go/src/pkg/net/http/server.go:1698 +0x91
net/http.(_Server).ListenAndServe(0xc2080fe480, 0x0, 0x0)
        /usr/local/go/src/pkg/net/http/server.go:1688 +0x14d
net/http.ListenAndServe(0xc2080ed3a7, 0x5, 0x7fae15807868, 0xc2080e6c90, 0x0, 0x0)
        /usr/local/go/src/pkg/net/http/server.go:1778 +0x79
github.com/codegangsta/negroni.(*Negroni).Run(0xc2080e6c90, 0xc2080ed3a7, 0x5)
        /home/juno/workspace/gocode/src/github.com/codegangsta/negroni/negroni.go:92 +0x1fe
github.com/danjac/photoshare.Serve()
        /home/juno/workspace/gocode/src/github.com/danjac/photoshare/commands.go:28 +0x225
main.main()
        /home/juno/git/fromGitHub/photoshare/commands/server/main.go:6 +0x1a

**Comment by xzdev** [comment]
In storage.go, there are bugs in switch statement. Should remove break in each switch case and add **fallthrough** between the following switch case.

```
    case "image/jpeg":
    case "image/jpg":
```
